version: '3.3'

services:
  web:
    build: ./ 
    command: gunicorn beauty_city.wsgi --bind 0.0.0.0:8000
    env_file:
      - ./beauty_city/.env
    volumes:
      - static_data:/home/www/app/staticfiles
      - media_data:/home/www/app/media
    expose:
      - 8000
  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - web 
    ports:
      - "80:80"
    volumes:
      - static_data:/home/www/app/staticfiles
      - media_data:/home/www/app/media
      - ./nginx:/etc/nginx/conf.d
volumes:
  static_data:
  media_data:
