version: '3.3'

services:
  web:
    build: ./ 
    command: gunicorn beauty_city.wsgi --bind 0.0.0.0:8000
    env_file:
      - ./.env
    volumes:
      - ./:/app/
      - static_data:/app/staticfiles
    expose:
      - 8000
  nginx:
    image: nginx:1.21-alpine
    depends_on:
      - web 
    ports:
      - "80:80"
    volumes:
      - static_data:/app/staticfiles
      - ./nginx:/etc/nginx/conf.d
volumes:
  static_data:
