# Generated by Django 3.2.16 on 2022-12-13 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='имя мастера')),
                ('last_name', models.CharField(max_length=100, verbose_name='имя мастера')),
                ('rating', models.FloatField(help_text='Хардкод пока нет реальных отзывов', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='оценка')),
                ('review_count', models.PositiveSmallIntegerField(help_text='Хардкод пока нет реальных отзывов', verbose_name='количество отзывов')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='фото мастера')),
                ('start_experience_date', models.DateField(help_text='для расчета стажа', verbose_name='дата начала рабочего стажа')),
            ],
            options={
                'verbose_name': 'мастер',
                'verbose_name_plural': 'мастера',
            },
        ),
        migrations.CreateModel(
            name='MasterSpeciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
            ],
            options={
                'verbose_name': 'специальность',
                'verbose_name_plural': 'специальности',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена без промо')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
            ],
            options={
                'verbose_name': 'тип платежа',
                'verbose_name_plural': 'типы платежей',
            },
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='название компании')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='описание компании')),
                ('code', models.CharField(max_length=20, verbose_name='промо код')),
                ('is_active', models.BooleanField(default=False, verbose_name='статус активности')),
                ('percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='скидка в процентах')),
                ('absolute', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='абсолютная скидка')),
            ],
        ),
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='заглавное фото салона')),
            ],
            options={
                'verbose_name': 'салон красоты',
                'verbose_name_plural': 'салоны красоты',
            },
        ),
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('order', models.IntegerField(help_text='чем меньше число, тем раньше', verbose_name='порядок отображения группы')),
            ],
            options={
                'verbose_name': 'группа услуг',
                'verbose_name_plural': 'группы услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='заглавное фото услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('order', models.IntegerField(help_text='чем меньше число, тем раньше', verbose_name='порядок отображения внутри группы')),
                ('duration_in_minutes', models.PositiveSmallIntegerField(help_text='чтобы понимать при записи ближайшее свободное время', verbose_name='длительность услуги в минутах')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='saloonapp.servicegroup')),
            ],
            options={
                'verbose_name': 'услуга',
                'verbose_name_plural': 'услуги',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='дата и время оплаты')),
                ('status', models.CharField(choices=[('Отменен', 'Cancelled'), ('Оплачен', 'Paid')], max_length=10, verbose_name='статус платежа')),
                ('ptype', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='saloonapp.paymenttype')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежи',
            },
        ),
    ]
