# Generated by Django 3.2.16 on 2022-12-13 20:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saloonapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to='saloonapp.master'),
        ),
        migrations.AddField(
            model_name='note',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='saloonapp.payment'),
        ),
        migrations.AddField(
            model_name='note',
            name='promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to='saloonapp.promo'),
        ),
        migrations.AddField(
            model_name='note',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to='saloonapp.service'),
        ),
        migrations.AddField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='master',
            name='services',
            field=models.ManyToManyField(to='saloonapp.Service'),
        ),
        migrations.AddField(
            model_name='master',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='saloonapp.masterspeciality'),
        ),
    ]
