# Generated by Django 3.2.16 on 2022-12-14 10:38

from django.db import migrations, models
import saloonapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0003_alter_saloon_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[saloonapp.validators.validate_svg_file_extension], verbose_name='фото мастера'),
        ),
        migrations.AlterField(
            model_name='service',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[saloonapp.validators.validate_svg_file_extension], verbose_name='заглавное фото услуги'),
        ),
    ]
