# Generated by Django 3.2.16 on 2022-12-14 11:29

from django.db import migrations, models
import saloonapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0004_auto_20221214_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='rating',
        ),
        migrations.AddField(
            model_name='master',
            name='rating_image',
            field=models.FileField(blank=True, help_text='Хардкод пока нет реальных отзывов', null=True, upload_to='', validators=[saloonapp.validators.validate_svg_file_extension], verbose_name='картинка оценки'),
        ),
        migrations.AlterField(
            model_name='master',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='фамилия мастера'),
        ),
    ]
