# Generated by Django 3.2.16 on 2022-12-14 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0006_auto_20221214_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'записи'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'verbose_name': 'таймслот', 'verbose_name_plural': 'таймслоты'},
        ),
        migrations.AddField(
            model_name='note',
            name='saloon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to='saloonapp.saloon'),
        ),
    ]
