# Generated by Django 3.2.16 on 2022-12-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0008_auto_20221214_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(null=True, verbose_name='дата и время платежа'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(verbose_name='дата и время создания счета'),
        ),
    ]
