# Generated by Django 3.2.16 on 2022-12-18 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0010_auto_20221215_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='saloonapp.payment'),
        ),
    ]
