# Generated by Django 3.2.16 on 2022-12-18 19:05

from django.db import migrations, models
import django.db.models.deletion
import saloonapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0012_alter_payment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='ptype',
            field=models.ForeignKey(default=saloonapp.models.PaymentType.get_default_pk, on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='saloonapp.paymenttype'),
        ),
    ]
