# Generated by Django 3.2.16 on 2022-12-19 16:58
import datetime

from django.db import migrations


def set_default_saloon_for_note(apps, schema_editor):
    Saloon = apps.get_model('saloonapp', 'Saloon')
    Note = apps.get_model('saloonapp', 'Note')

    notes = Note.objects.filter(saloon__isnull=True)
    if notes:
        obj, created = Saloon.objects.get_or_create(
            name='Салон миграция', address='Дефолтный адрес', city='Дефолтный город')
        notes.update(saloon=obj)


def set_default_saloon_for_note_reverse(apps, schema_editor):
    Saloon = apps.get_model('saloonapp', 'Saloon')
    Note = apps.get_model('saloonapp', 'Note')

    obj, created = Saloon.objects.get_or_create(
        name='Салон миграция', address='Дефолтный адрес', city='Дефолтный город')
    notes = Note.objects.filter(saloon=obj)
    if notes:
        notes.update(saloon=None)
    obj.delete()

def set_default_date_stime_etime(apps, schema_editor):
    Note = apps.get_model('saloonapp', 'Note')
    default_date = datetime.date(2000, 1, 1)
    default_stime = datetime.time(0, 13)
    default_etime = datetime.time(0, 14)

    Note.objects.filter(date__isnull=True).update(date=default_date)
    Note.objects.filter(stime__isnull=True).update(stime=default_stime)
    Note.objects.filter(etime__isnull=True).update(etime=default_etime)


def set_default_date_stime_etime_reverse(apps, schema_editor):
    Note = apps.get_model('saloonapp', 'Note')
    default_date = datetime.date(2000, 1, 1)
    default_stime = datetime.time(0, 13)
    default_etime = datetime.time(0, 14)

    Note.objects.filter(date=default_date).update(date=None)
    Note.objects.filter(stime=default_stime).update(stime=None)
    Note.objects.filter(etime=default_etime).update(etime=None)


class Migration(migrations.Migration):
    dependencies = [
        ('saloonapp', '0014_alter_master_services'),
    ]

    operations = [
        migrations.RunPython(set_default_saloon_for_note, set_default_saloon_for_note_reverse),
        migrations.RunPython(set_default_date_stime_etime, set_default_date_stime_etime_reverse)
    ]
