# Generated by Django 3.2.16 on 2022-12-19 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloonapp', '0015_auto_20221219_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateField(verbose_name='дата записи'),
        ),
        migrations.AlterField(
            model_name='note',
            name='etime',
            field=models.TimeField(verbose_name='время окончания'),
        ),
        migrations.AlterField(
            model_name='note',
            name='saloon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='notes', to='saloonapp.saloon'),
        ),
        migrations.AlterField(
            model_name='note',
            name='stime',
            field=models.TimeField(verbose_name='время начала'),
        ),
    ]
