# Generated by Django 3.2.16 on 2022-12-14 12:27

from django.db import migrations, models
import saloonapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[saloonapp.validators.validate_svg_file_extension], verbose_name='заглавное фото салона'),
        ),
    ]
